config/routes.rb
Growify::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :vegetables
  resources :families
  resources :varieties

  root  'static_pages#home'
  
  match '/signup',  to: 'users#new',            via: 'get' 
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  

end

app/controllers/vegetables_controller.rb
class VegetablesController < ApplicationController

  def index
    @vegetables = Vegetable.all
    @families = Family.all
  end

  def show
    @veg = Vegetable.find(params[:id])
    @info = @veg.info
  end

  def new
  end

end

app/helpers/vegetables_helper.rb
module VegetablesHelper
end

app/views/vegetables/index.html.erb
<h1>Vegetables</h1>

<% @families.each do |fam| %>
<table class="table table-striped table-hover table-condensed table-bordered items-table">
  <thead>
    <tr>
      <th><%= "#{fam.common_name} (#{fam.family_name})" %></th>
    </tr>
  </thead>
  <tbody>
<% fam.vegetables.each do |veg| %>
    <tr>
      <td><%= link_to veg.name, vegetable_path(veg.id) %></td>
    </tr>
<% end %>
  </tbody>
</table>
<% end %>

app/views/vegetables/show.html.erb
<h1><%= @veg.name %></h1>
<h2><%= @veg.family.common_name %> - <i><%= @veg.family.family_name %> </i></h2>
<small><%= @info %></small>
<h3>Varieties</h3>
<ul>
  <li>First Variety</li>
  <li>Second variety</li>
  <li>..etc..etc</li>
</ul>